import { createSlice } from '@reduxjs/toolkit';

const initialState = [
  {
    ID: 12341,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12342,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12343,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12344,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12345,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12346,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12347,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
  {
    ID: 12348,
    Name: 'مستشفى الأمل',
    'Old ID': 'HOSP-9876',
    Category: 'Hospital',
    Branches: 'Riyadh, Jeddah',
    Status: 'Active',
    'Batch Due Days': 30,
    'Provider Class': 'A+',
    Priority: 'High',
    'Latest Clearance': '2025-08-15',
    'Tax Number': '3100456789',
    Online: 'Yes',
    'Allow Chronic Portal': 'Allowed',
  },
];

const providersSlice = createSlice({
  name: 'providers',
  initialState,
  reducers: {
    changeProvidersData: (state, action) => {
      state = action.payload;
    },
  },
});

export const { changeProvidersData } = providersSlice.actions;
export default providersSlice.reducer;
