import { createSlice } from '@reduxjs/toolkit';

// Sample data rows
const initialState = [
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
  {
    ID: 2171,
    Name: 'Mercure Ismailia Hotel',
    OldID: 'CO-0371',
    Category: 'Hotels',
    Type: 'Corporate',
    Member: 136,
    Branch: 1,
    Status: 'Activated',
    'Change Status': ['Green', 'Red', 'Yellow', 'Blue'],
  },
];

const clientsSlice = createSlice({
  name: 'clients',
  initialState,
  reducers: {
    changeClientsData(state, action) {
      state = action.payload;
    },
  },
});

export const { changeClientsData } = clientsSlice.actions;
export default clientsSlice.reducer;
